cursor #efe0d3
cursor_text_color #d9c3af

foreground #efe0d3
background #100c07
background_opacity 1
selection_foreground #482a02
selection_background #efbd88
url_color #ffb867

# black
color0 #221a12
color8 #3d3630

# red
color1 #ffb595
color9 #ffc7af

# green
color2 #f0ffcc
color10 #f8ffe6

# yellow
color3 #ffffff
color11 #ffffff

# blue
color4 #ffb867
color12 #e1d7ff

# magenta
color5 #ffafd6
color13 #ffc9e3

# cyan
color6 #ffffff
color14 #ffffff

# white
color7 #a18d7b
color15 #efe0d3

